### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by Janx0102** [parameterlab/trap#2]
I‘d like to know the specific version of Python you used during the experiment. I tried 3.8, 3.9, and 3.10, but none of them matched the requirements. txt file. Thank you!

**Comment by Framartin** [comment]
Hello @Janx0102 ,
Thanks for your interest in our paper. I just checked, and we used Python 3.8.13. You may need to adapt the PyTorch version (and its related packages) to match your CUDA version.
I remain available if you wish further help.
